// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    user_id, title, slug, description, 
    location, start_time, type, status
    )
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
    ) RETURNING id, user_id, title, slug, description, location, start_time, type, status, created_at
`

type CreateEventParams struct {
	UserID      string           `json:"user_id"`
	Title       string           `json:"title"`
	Slug        string           `json:"slug"`
	Description string           `json:"description"`
	Location    string           `json:"location"`
	StartTime   pgtype.Timestamp `json:"start_time"`
	Type        EventType        `json:"type"`
	Status      EventStatus      `json:"status"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.UserID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.Type,
		arg.Status,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :one
DELETE FROM events WHERE id = $1 RETURNING id, user_id, title, slug, description, location, start_time, type, status, created_at
`

func (q *Queries) DeleteEvent(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRow(ctx, deleteEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const findEventByID = `-- name: FindEventByID :one
SELECT id, user_id, title, slug, description, location, start_time, type, status, created_at FROM events WHERE id = $1
`

func (q *Queries) FindEventByID(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRow(ctx, findEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getEventByHostIDAndTitle = `-- name: GetEventByHostIDAndTitle :one
SELECT id, user_id, title, slug, description, location, start_time, type, status, created_at FROM events WHERE user_id = $1 AND title = $2
`

type GetEventByHostIDAndTitleParams struct {
	UserID string `json:"user_id"`
	Title  string `json:"title"`
}

func (q *Queries) GetEventByHostIDAndTitle(ctx context.Context, arg GetEventByHostIDAndTitleParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByHostIDAndTitle, arg.UserID, arg.Title)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getEventStats = `-- name: GetEventStats :one
SELECT 
    e.id AS event_id,
    e.title,
    e.slug,
    e.status AS event_status,
    e.start_time,
    
    -- Guest Metrics for this single event
    COUNT(g.id) AS total_guests_invited,
    COUNT(CASE WHEN g.rsvp_status = 'attending' THEN 1 END) AS total_guests_confirmed,
    COUNT(CASE WHEN g.is_checked_in = TRUE THEN 1 END) AS total_guests_checked_in,
    
    -- Attendance Success Rate
    CASE 
        WHEN COUNT(g.id) > 0 THEN 
            ROUND((COUNT(CASE WHEN g.is_checked_in = TRUE THEN 1 END)::NUMERIC / COUNT(g.id)::NUMERIC) * 100, 2)
        ELSE 0 
    END AS attendance_rate_percentage

FROM events e
LEFT JOIN guests g ON e.id = g.event_id
WHERE e.id = $1
GROUP BY e.id
`

type GetEventStatsRow struct {
	EventID                  string           `json:"event_id"`
	Title                    string           `json:"title"`
	Slug                     string           `json:"slug"`
	EventStatus              EventStatus      `json:"event_status"`
	StartTime                pgtype.Timestamp `json:"start_time"`
	TotalGuestsInvited       int64            `json:"total_guests_invited"`
	TotalGuestsConfirmed     int64            `json:"total_guests_confirmed"`
	TotalGuestsCheckedIn     int64            `json:"total_guests_checked_in"`
	AttendanceRatePercentage int32            `json:"attendance_rate_percentage"`
}

func (q *Queries) GetEventStats(ctx context.Context, id string) (GetEventStatsRow, error) {
	row := q.db.QueryRow(ctx, getEventStats, id)
	var i GetEventStatsRow
	err := row.Scan(
		&i.EventID,
		&i.Title,
		&i.Slug,
		&i.EventStatus,
		&i.StartTime,
		&i.TotalGuestsInvited,
		&i.TotalGuestsConfirmed,
		&i.TotalGuestsCheckedIn,
		&i.AttendanceRatePercentage,
	)
	return i, err
}

const getUserEventStats = `-- name: GetUserEventStats :one
SELECT 
    e.user_id,
    
    -- Event Metrics
    COUNT(DISTINCT e.id) AS total_events,
    COUNT(DISTINCT CASE WHEN e.status = 'open' THEN e.id END) AS open_events,
    COUNT(DISTINCT CASE WHEN e.status = 'closed' THEN e.id END) AS closed_events,
    COUNT(DISTINCT CASE WHEN e.status = 'cancelled' THEN e.id END) AS cancelled_events,
    
    -- Guest Metrics
    COUNT(g.id) AS total_guests_invited,
    COUNT(CASE WHEN g.rsvp_status = 'attending' THEN 1 END) AS total_guests_confirmed,
    COUNT(CASE WHEN g.is_checked_in = TRUE THEN 1 END) AS total_guests_checked_in,
    
    -- Attendance Success Rate
    CASE 
        WHEN COUNT(g.id) > 0 THEN 
            ((COUNT(CASE WHEN g.is_checked_in = TRUE THEN 1 END)::NUMERIC / COUNT(g.id)::NUMERIC) * 100)::INTEGER
        ELSE 0 
    END AS attendance_rate_percentage

FROM events e
LEFT JOIN guests g ON e.id = g.event_id
WHERE e.user_id = $1
GROUP BY e.user_id
`

type GetUserEventStatsRow struct {
	UserID                   string `json:"user_id"`
	TotalEvents              int64  `json:"total_events"`
	OpenEvents               int64  `json:"open_events"`
	ClosedEvents             int64  `json:"closed_events"`
	CancelledEvents          int64  `json:"cancelled_events"`
	TotalGuestsInvited       int64  `json:"total_guests_invited"`
	TotalGuestsConfirmed     int64  `json:"total_guests_confirmed"`
	TotalGuestsCheckedIn     int64  `json:"total_guests_checked_in"`
	AttendanceRatePercentage int32  `json:"attendance_rate_percentage"`
}

func (q *Queries) GetUserEventStats(ctx context.Context, userID string) (GetUserEventStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserEventStats, userID)
	var i GetUserEventStatsRow
	err := row.Scan(
		&i.UserID,
		&i.TotalEvents,
		&i.OpenEvents,
		&i.ClosedEvents,
		&i.CancelledEvents,
		&i.TotalGuestsInvited,
		&i.TotalGuestsConfirmed,
		&i.TotalGuestsCheckedIn,
		&i.AttendanceRatePercentage,
	)
	return i, err
}

const getUserEvents = `-- name: GetUserEvents :many
SELECT id, user_id, title, slug, description, location, start_time, type, status, created_at FROM events WHERE user_id = $1
`

func (q *Queries) GetUserEvents(ctx context.Context, userID string) ([]Event, error) {
	rows, err := q.db.Query(ctx, getUserEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, user_id, title, slug, description, location, start_time, type, status, created_at FROM events
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    location = COALESCE($4, location),
    start_time = COALESCE($5, start_time),
    type = COALESCE($6, type),
    status = COALESCE($7, status)
WHERE id = $1 RETURNING id, user_id, title, slug, description, location, start_time, type, status, created_at
`

type UpdateEventParams struct {
	ID          string           `json:"id"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Location    string           `json:"location"`
	StartTime   pgtype.Timestamp `json:"start_time"`
	Type        EventType        `json:"type"`
	Status      EventStatus      `json:"status"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.Type,
		arg.Status,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
