// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guests.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkGuestExists = `-- name: CheckGuestExists :one
SELECT EXISTS (
    SELECT 1 FROM guests 
    WHERE event_id = $1 AND LOWER(TRIM(name)) = LOWER(TRIM($2))
)
`

type CheckGuestExistsParams struct {
	EventID string `json:"event_id"`
	Btrim   string `json:"btrim"`
}

func (q *Queries) CheckGuestExists(ctx context.Context, arg CheckGuestExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkGuestExists, arg.EventID, arg.Btrim)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createGuest = `-- name: CreateGuest :one
INSERT INTO guests (
    event_id, name, email, phone, 
    rsvp_status, rsvp_token, ticket_code,
    is_checked_in, checked_in_at
) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, event_id, name, email, phone, rsvp_status, rsvp_token, ticket_code, is_checked_in, checked_in_at, created_at
`

type CreateGuestParams struct {
	EventID     string           `json:"event_id"`
	Name        string           `json:"name"`
	Email       pgtype.Text      `json:"email"`
	Phone       pgtype.Text      `json:"phone"`
	RsvpStatus  RsvpStatus       `json:"rsvp_status"`
	RsvpToken   pgtype.Text      `json:"rsvp_token"`
	TicketCode  pgtype.Text      `json:"ticket_code"`
	IsCheckedIn bool             `json:"is_checked_in"`
	CheckedInAt pgtype.Timestamp `json:"checked_in_at"`
}

func (q *Queries) CreateGuest(ctx context.Context, arg CreateGuestParams) (Guest, error) {
	row := q.db.QueryRow(ctx, createGuest,
		arg.EventID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.RsvpStatus,
		arg.RsvpToken,
		arg.TicketCode,
		arg.IsCheckedIn,
		arg.CheckedInAt,
	)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.RsvpStatus,
		&i.RsvpToken,
		&i.TicketCode,
		&i.IsCheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGuest = `-- name: DeleteGuest :one
DELETE FROM guests WHERE id = $1 RETURNING id, event_id, name, email, phone, rsvp_status, rsvp_token, ticket_code, is_checked_in, checked_in_at, created_at
`

func (q *Queries) DeleteGuest(ctx context.Context, id string) (Guest, error) {
	row := q.db.QueryRow(ctx, deleteGuest, id)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.RsvpStatus,
		&i.RsvpToken,
		&i.TicketCode,
		&i.IsCheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
	)
	return i, err
}

const findGuestByID = `-- name: FindGuestByID :one
SELECT 
    g.id AS guest_id,
    g.name AS guest_name,
    g.email AS guest_email,
    g.phone AS guest_phone,
    g.rsvp_status,
    g.ticket_code,
    g.is_checked_in,
    e.id AS event_id,
    e.user_id as host_id,
    e.title AS event_title,
    e.slug AS event_slug,
    e.description AS event_description,
    e.location AS event_title_location,
    e.start_time AS event_start_time
FROM guests g
INNER JOIN events e ON g.event_id = e.id
WHERE g.id = $1
`

type FindGuestByIDRow struct {
	GuestID            string           `json:"guest_id"`
	GuestName          string           `json:"guest_name"`
	GuestEmail         pgtype.Text      `json:"guest_email"`
	GuestPhone         pgtype.Text      `json:"guest_phone"`
	RsvpStatus         RsvpStatus       `json:"rsvp_status"`
	TicketCode         pgtype.Text      `json:"ticket_code"`
	IsCheckedIn        bool             `json:"is_checked_in"`
	EventID            string           `json:"event_id"`
	HostID             string           `json:"host_id"`
	EventTitle         string           `json:"event_title"`
	EventSlug          string           `json:"event_slug"`
	EventDescription   string           `json:"event_description"`
	EventTitleLocation string           `json:"event_title_location"`
	EventStartTime     pgtype.Timestamp `json:"event_start_time"`
}

func (q *Queries) FindGuestByID(ctx context.Context, id string) (FindGuestByIDRow, error) {
	row := q.db.QueryRow(ctx, findGuestByID, id)
	var i FindGuestByIDRow
	err := row.Scan(
		&i.GuestID,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.RsvpStatus,
		&i.TicketCode,
		&i.IsCheckedIn,
		&i.EventID,
		&i.HostID,
		&i.EventTitle,
		&i.EventSlug,
		&i.EventDescription,
		&i.EventTitleLocation,
		&i.EventStartTime,
	)
	return i, err
}

const getGuestsByEventID = `-- name: GetGuestsByEventID :many
SELECT id, event_id, name, email, phone, rsvp_status, ticket_code, is_checked_in 
FROM guests 
WHERE event_id = $1
`

type GetGuestsByEventIDRow struct {
	ID          string      `json:"id"`
	EventID     string      `json:"event_id"`
	Name        string      `json:"name"`
	Email       pgtype.Text `json:"email"`
	Phone       pgtype.Text `json:"phone"`
	RsvpStatus  RsvpStatus  `json:"rsvp_status"`
	TicketCode  pgtype.Text `json:"ticket_code"`
	IsCheckedIn bool        `json:"is_checked_in"`
}

func (q *Queries) GetGuestsByEventID(ctx context.Context, eventID string) ([]GetGuestsByEventIDRow, error) {
	rows, err := q.db.Query(ctx, getGuestsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGuestsByEventIDRow
	for rows.Next() {
		var i GetGuestsByEventIDRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.RsvpStatus,
			&i.TicketCode,
			&i.IsCheckedIn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRsvpGuestByToken = `-- name: GetRsvpGuestByToken :one
SELECT id, event_id, name, email, phone, rsvp_status, rsvp_token, ticket_code, is_checked_in, checked_in_at, created_at FROM guests 
WHERE id = $1 AND rsvp_token = $2 AND rsvp_status = 'pending'
LIMIT 1
FOR UPDATE
`

type GetRsvpGuestByTokenParams struct {
	ID        string      `json:"id"`
	RsvpToken pgtype.Text `json:"rsvp_token"`
}

func (q *Queries) GetRsvpGuestByToken(ctx context.Context, arg GetRsvpGuestByTokenParams) (Guest, error) {
	row := q.db.QueryRow(ctx, getRsvpGuestByToken, arg.ID, arg.RsvpToken)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.RsvpStatus,
		&i.RsvpToken,
		&i.TicketCode,
		&i.IsCheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
	)
	return i, err
}

const listGuests = `-- name: ListGuests :many
SELECT id, event_id, name, email, phone, rsvp_status, rsvp_token, ticket_code, is_checked_in, checked_in_at, created_at FROM guests
`

func (q *Queries) ListGuests(ctx context.Context) ([]Guest, error) {
	rows, err := q.db.Query(ctx, listGuests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guest
	for rows.Next() {
		var i Guest
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.RsvpStatus,
			&i.RsvpToken,
			&i.TicketCode,
			&i.IsCheckedIn,
			&i.CheckedInAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuest = `-- name: UpdateGuest :one
UPDATE guests SET
    event_id = COALESCE($2, event_id),
    name = COALESCE($3, name),
    email = COALESCE($4, email),
    phone = COALESCE($5, phone),
    rsvp_status = COALESCE($6, rsvp_status),
    rsvp_token = COALESCE($7, rsvp_token),
    ticket_code = COALESCE($8, ticket_code),
    is_checked_in = COALESCE($9, is_checked_in),
    checked_in_at = COALESCE($10, checked_in_at)
WHERE id = $1 RETURNING id, event_id, name, email, phone, rsvp_status, rsvp_token, ticket_code, is_checked_in, checked_in_at, created_at
`

type UpdateGuestParams struct {
	ID          string           `json:"id"`
	EventID     string           `json:"event_id"`
	Name        string           `json:"name"`
	Email       pgtype.Text      `json:"email"`
	Phone       pgtype.Text      `json:"phone"`
	RsvpStatus  RsvpStatus       `json:"rsvp_status"`
	RsvpToken   pgtype.Text      `json:"rsvp_token"`
	TicketCode  pgtype.Text      `json:"ticket_code"`
	IsCheckedIn bool             `json:"is_checked_in"`
	CheckedInAt pgtype.Timestamp `json:"checked_in_at"`
}

func (q *Queries) UpdateGuest(ctx context.Context, arg UpdateGuestParams) (Guest, error) {
	row := q.db.QueryRow(ctx, updateGuest,
		arg.ID,
		arg.EventID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.RsvpStatus,
		arg.RsvpToken,
		arg.TicketCode,
		arg.IsCheckedIn,
		arg.CheckedInAt,
	)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.RsvpStatus,
		&i.RsvpToken,
		&i.TicketCode,
		&i.IsCheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
	)
	return i, err
}
