// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type EventStatus string

const (
	EventStatusOpen      EventStatus = "open"
	EventStatusClosed    EventStatus = "closed"
	EventStatusCancelled EventStatus = "cancelled"
)

func (e *EventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventStatus(s)
	case string:
		*e = EventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EventStatus: %T", src)
	}
	return nil
}

type NullEventStatus struct {
	EventStatus EventStatus `json:"event_status"`
	Valid       bool        `json:"valid"` // Valid is true if EventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventStatus), nil
}

type EventType string

const (
	EventTypePublic   EventType = "public"
	EventTypePrivate  EventType = "private"
	EventTypeReserved EventType = "reserved"
)

func (e *EventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventType(s)
	case string:
		*e = EventType(s)
	default:
		return fmt.Errorf("unsupported scan type for EventType: %T", src)
	}
	return nil
}

type NullEventType struct {
	EventType EventType `json:"event_type"`
	Valid     bool      `json:"valid"` // Valid is true if EventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventType) Scan(value interface{}) error {
	if value == nil {
		ns.EventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventType), nil
}

type RsvpStatus string

const (
	RsvpStatusPending   RsvpStatus = "pending"
	RsvpStatusAttending RsvpStatus = "attending"
	RsvpStatusDeclined  RsvpStatus = "declined"
)

func (e *RsvpStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RsvpStatus(s)
	case string:
		*e = RsvpStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RsvpStatus: %T", src)
	}
	return nil
}

type NullRsvpStatus struct {
	RsvpStatus RsvpStatus `json:"rsvp_status"`
	Valid      bool       `json:"valid"` // Valid is true if RsvpStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRsvpStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RsvpStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RsvpStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRsvpStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RsvpStatus), nil
}

type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
	UserRoleGuest UserRole = "guest"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Event struct {
	ID          string           `json:"id"`
	UserID      string           `json:"user_id"`
	Title       string           `json:"title"`
	Slug        string           `json:"slug"`
	Description string           `json:"description"`
	Location    string           `json:"location"`
	StartTime   pgtype.Timestamp `json:"start_time"`
	Type        EventType        `json:"type"`
	Status      EventStatus      `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Guest struct {
	ID          string           `json:"id"`
	EventID     string           `json:"event_id"`
	Name        string           `json:"name"`
	Email       pgtype.Text      `json:"email"`
	Phone       pgtype.Text      `json:"phone"`
	RsvpStatus  RsvpStatus       `json:"rsvp_status"`
	RsvpToken   pgtype.Text      `json:"rsvp_token"`
	TicketCode  pgtype.Text      `json:"ticket_code"`
	IsCheckedIn bool             `json:"is_checked_in"`
	CheckedInAt pgtype.Timestamp `json:"checked_in_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type PasswordReset struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

type User struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Email      string             `json:"email"`
	Password   string             `json:"password"`
	Phone      pgtype.Text        `json:"phone"`
	Role       UserRole           `json:"role"`
	IsActive   bool               `json:"is_active"`
	IsVerified bool               `json:"is_verified"`
	IsDeleted  bool               `json:"is_deleted"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
