// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	CheckGuestExists(ctx context.Context, arg CheckGuestExistsParams) (bool, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateGuest(ctx context.Context, arg CreateGuestParams) (Guest, error)
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteEvent(ctx context.Context, id string) (Event, error)
	DeleteGuest(ctx context.Context, id string) (Guest, error)
	DeleteUser(ctx context.Context, id string) (User, error)
	FindEventByID(ctx context.Context, id string) (Event, error)
	FindGuestByID(ctx context.Context, id string) (FindGuestByIDRow, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id string) (User, error)
	GetEventByHostIDAndTitle(ctx context.Context, arg GetEventByHostIDAndTitleParams) (Event, error)
	GetEventStats(ctx context.Context, id string) (GetEventStatsRow, error)
	GetGuestsByEventID(ctx context.Context, eventID string) ([]GetGuestsByEventIDRow, error)
	GetPasswordResetByTokenHash(ctx context.Context, tokenHash string) (PasswordReset, error)
	GetRsvpGuestByToken(ctx context.Context, arg GetRsvpGuestByTokenParams) (Guest, error)
	GetUserEventStats(ctx context.Context, userID string) (GetUserEventStatsRow, error)
	GetUserEvents(ctx context.Context, userID string) ([]Event, error)
	InvalidatePasswordReset(ctx context.Context, id string) (int64, error)
	ListEvents(ctx context.Context) ([]Event, error)
	ListGuests(ctx context.Context) ([]Guest, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateGuest(ctx context.Context, arg UpdateGuestParams) (Guest, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
